/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import static com.eldoraludo.ppafadministration.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafadministration.domain.Frais;
import com.eldoraludo.ppafadministration.repository.FraisRepository;
import com.eldoraludo.ppafadministration.web.converter.domain.FraisConverter;
import com.eldoraludo.ppafadministration.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class FraisController {
    private static final long serialVersionUID = 1L;

    @Inject
    private FraisRepository fraisRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private FraisConverter fraisConverter;

    public Frais newIfNull(Frais frais) {
        if (frais != null) {
            return frais;
        }

        return fraisRepository.getNewWithDefaults();
    }

    public boolean save(Frais frais) {
        fraisRepository.save(frais);
        messageUtil.info("status_saved_ok", fraisConverter.print(frais));
        return true;
    }

    public boolean saveAndClose(Frais frais) {
        fraisRepository.save(frais);
        messageUtil.infoDelayed("status_saved_ok", fraisConverter.print(frais));
        forceClose();
        return true;
    }

    public boolean delete(Frais frais) {
        String infoArg = fraisConverter.print(frais);
        fraisRepository.delete(frais);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}