/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.LieudedepotSelector.newLieudedepotSelector;
import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDate.newRangeDate;
import static com.eldoraludo.ppafadministration.domain.Suividulieudedepot_.date;
import static com.eldoraludo.ppafadministration.domain.Suividulieudedepot_.lieudedepotId;
import static com.eldoraludo.ppafadministration.domain.Suividulieudedepot_.membreppafId;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.LieudedepotSelector;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDate;
import com.eldoraludo.ppafadministration.domain.Suividulieudedepot;
import com.eldoraludo.ppafadministration.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for suividulieudedepot search.
 */
@Component
@Scope("session")
public class SuividulieudedepotSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Suividulieudedepot suividulieudedepot = new Suividulieudedepot();
    private RangeDate<Suividulieudedepot> dateRange = newRangeDate(date);
    private MembreppafSelector<Suividulieudedepot> membreppafSelector = newMembreppafSelector(membreppafId);
    private LieudedepotSelector<Suividulieudedepot> lieudedepotSelector = newLieudedepotSelector(lieudedepotId);

    public Suividulieudedepot getSuividulieudedepot() {
        return suividulieudedepot;
    }

    // Ranges, used from the view.
    public RangeDate<Suividulieudedepot> getDateRange() {
        return dateRange;
    }

    // Selectors for x-to-one associations
    public MembreppafSelector<Suividulieudedepot> getMembreppafSelector() {
        return membreppafSelector;
    }

    public LieudedepotSelector<Suividulieudedepot> getLieudedepotSelector() {
        return lieudedepotSelector;
    }
}