/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafadministration.dao.support.PropertySelectors.BooleanSelector.newBooleanSelector;
import static com.eldoraludo.ppafadministration.domain.Utilisateur_.enabled;
import static com.eldoraludo.ppafadministration.domain.Utilisateur_.membreppafId;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafadministration.dao.support.PropertySelectors.BooleanSelector;
import com.eldoraludo.ppafadministration.domain.Utilisateur;
import com.eldoraludo.ppafadministration.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for utilisateur search.
 */
@Component
@Scope("session")
public class UtilisateurSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Utilisateur utilisateur = new Utilisateur();
    private BooleanSelector<Utilisateur> enabledSelector = newBooleanSelector(enabled);
    private MembreppafSelector<Utilisateur> membreppafSelector = newMembreppafSelector(membreppafId);

    public Utilisateur getUtilisateur() {
        return utilisateur;
    }

    // Selectors for property
    public BooleanSelector<Utilisateur> getEnabledSelector() {
        return enabledSelector;
    }

    // Selectors for x-to-one associations
    public MembreppafSelector<Utilisateur> getMembreppafSelector() {
        return membreppafSelector;
    }
}