/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.eldoraludo.ppafadministration.dao.support.SearchParameters;
import com.eldoraludo.ppafadministration.domain.Utilisateur;
import com.eldoraludo.ppafadministration.repository.UtilisateurRepository;
import com.eldoraludo.ppafadministration.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class UtilisateurLazyDataModel extends GenericLazyDataModel<Utilisateur> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private UtilisateurRepository utilisateurRepository;
    @Inject
    transient private UtilisateurSearchForm utilisateurSearchForm;

    /**
     * Prepare the search parameters and call the utilisateurRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<Utilisateur> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = utilisateurSearchForm.getSearchParameters();

        // property selectors
        sp.clearPropertySelectors();
        sp.addPropertySelector(utilisateurSearchForm.getEnabledSelector());

        // entity selectors
        sp.clearEntitySelectors();
        sp.addEntitySelector(utilisateurSearchForm.getMembreppafSelector());

        Utilisateur utilisateur = utilisateurSearchForm.getUtilisateur();
        setRowCount(utilisateurRepository.findCount(utilisateur, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data

        return utilisateurRepository.find(utilisateur, sp);
    }
}