/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.ContactSelector.newContactSelector;
import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.ItemSelector.newItemSelector;
import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.LieudedepotSelector.newLieudedepotSelector;
import static com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDate.newRangeDate;
import static com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDouble.newRangeDouble;
import static com.eldoraludo.ppafadministration.dao.support.Ranges.RangeInteger.newRangeInteger;
import static com.eldoraludo.ppafadministration.domain.Vente_.contactId;
import static com.eldoraludo.ppafadministration.domain.Vente_.date;
import static com.eldoraludo.ppafadministration.domain.Vente_.datedencaissement;
import static com.eldoraludo.ppafadministration.domain.Vente_.fraisdeport;
import static com.eldoraludo.ppafadministration.domain.Vente_.itemId;
import static com.eldoraludo.ppafadministration.domain.Vente_.lieudedepotId;
import static com.eldoraludo.ppafadministration.domain.Vente_.membreppafId;
import static com.eldoraludo.ppafadministration.domain.Vente_.prixtotal;
import static com.eldoraludo.ppafadministration.domain.Vente_.quantite;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.ContactSelector;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.ItemSelector;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.LieudedepotSelector;
import com.eldoraludo.ppafadministration.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDate;
import com.eldoraludo.ppafadministration.dao.support.Ranges.RangeDouble;
import com.eldoraludo.ppafadministration.dao.support.Ranges.RangeInteger;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.eldoraludo.ppafadministration.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for vente search.
 */
@Component
@Scope("session")
public class VenteSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Vente vente = new Vente();
    private RangeDate<Vente> dateRange = newRangeDate(date);
    private RangeDate<Vente> datedencaissementRange = newRangeDate(datedencaissement);
    private RangeInteger<Vente> quantiteRange = newRangeInteger(quantite);
    private RangeDouble<Vente> prixtotalRange = newRangeDouble(prixtotal);
    private RangeDouble<Vente> fraisdeportRange = newRangeDouble(fraisdeport);
    private ItemSelector<Vente> itemSelector = newItemSelector(itemId);
    private MembreppafSelector<Vente> membreppafSelector = newMembreppafSelector(membreppafId);
    private LieudedepotSelector<Vente> lieudedepotSelector = newLieudedepotSelector(lieudedepotId);
    private ContactSelector<Vente> contactSelector = newContactSelector(contactId);

    public Vente getVente() {
        return vente;
    }

    // Ranges, used from the view.
    public RangeDate<Vente> getDateRange() {
        return dateRange;
    }

    public RangeDate<Vente> getDatedencaissementRange() {
        return datedencaissementRange;
    }

    public RangeInteger<Vente> getQuantiteRange() {
        return quantiteRange;
    }

    public RangeDouble<Vente> getPrixtotalRange() {
        return prixtotalRange;
    }

    public RangeDouble<Vente> getFraisdeportRange() {
        return fraisdeportRange;
    }

    // Selectors for x-to-one associations
    public ItemSelector<Vente> getItemSelector() {
        return itemSelector;
    }

    public MembreppafSelector<Vente> getMembreppafSelector() {
        return membreppafSelector;
    }

    public LieudedepotSelector<Vente> getLieudedepotSelector() {
        return lieudedepotSelector;
    }

    public ContactSelector<Vente> getContactSelector() {
        return contactSelector;
    }
}