/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.eldoraludo.ppafadministration.web.domain;

import java.util.List;
import java.util.Map;
import javax.inject.Inject;

import org.primefaces.model.SortOrder;

import com.eldoraludo.ppafadministration.dao.support.SearchParameters;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.eldoraludo.ppafadministration.repository.VenteRepository;
import com.eldoraludo.ppafadministration.web.domain.support.GenericLazyDataModel;

/**
 * Provides server-side pagination for search.
 *
 * @see http://jira.springframework.org/browse/SWF-1224 to avoid instanciate it as a var from your flow 
 */
public class VenteLazyDataModel extends GenericLazyDataModel<Vente> {
    private static final long serialVersionUID = 1L;

    @Inject
    transient private VenteRepository venteRepository;
    @Inject
    transient private VenteSearchForm venteSearchForm;

    /**
     * Prepare the search parameters and call the venteRepository finder.
     * Automatically called by PrimeFaces component.
     */
    @Override
    public List<Vente> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, String> filters) {
        SearchParameters sp = venteSearchForm.getSearchParameters();

        // ranges
        sp.clearRanges();
        sp.addRange(venteSearchForm.getDateRange());
        sp.addRange(venteSearchForm.getDatedencaissementRange());
        sp.addRange(venteSearchForm.getQuantiteRange());
        sp.addRange(venteSearchForm.getPrixtotalRange());
        sp.addRange(venteSearchForm.getFraisdeportRange());

        // entity selectors
        sp.clearEntitySelectors();
        sp.addEntitySelector(venteSearchForm.getItemSelector());
        sp.addEntitySelector(venteSearchForm.getMembreppafSelector());
        sp.addEntitySelector(venteSearchForm.getLieudedepotSelector());
        sp.addEntitySelector(venteSearchForm.getContactSelector());

        Vente vente = venteSearchForm.getVente();
        setRowCount(venteRepository.findCount(vente, sp)); // total count so the paginator may display the total number of pages
        populateSearchParameters(sp, first, pageSize, sortField, sortOrder, filters); // load one page of data

        return venteRepository.find(vente, sp);
    }
}