/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafadministration.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafadministration.domain.Frais;
import com.eldoraludo.ppafadministration.repository.FraisRepositoryImpl;
import com.eldoraludo.ppafadministration.dao.FraisDao;
import com.eldoraludo.ppafadministration.dao.support.SearchParameters;

/**
 * Unit test on FraisRepositoryImpl
 */
public class FraisRepositoryImplTest {

    private FraisRepositoryImpl fraisRepositoryImpl;
    private FraisDao fraisDao;

    @Before
    public void setUp() {
        // called before each test.
        fraisRepositoryImpl = new FraisRepositoryImpl();
        fraisDao = mock(FraisDao.class);
        fraisRepositoryImpl.setFraisDao(fraisDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Frais none = null;

        when(fraisDao.findUniqueOrNone(any(Frais.class), any(SearchParameters.class))).thenReturn(none);

        Frais result = fraisRepositoryImpl.findUniqueOrNone(new Frais());

        assertThat(result).isNull();
        verify(fraisDao, times(1)).findUniqueOrNone(any(Frais.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Frais unique = new Frais();

        when(fraisDao.findUniqueOrNone(any(Frais.class), any(SearchParameters.class))).thenReturn(unique);

        Frais result = fraisRepositoryImpl.findUniqueOrNone(new Frais());

        assertThat(result).isNotNull();
        verify(fraisDao, times(1)).findUniqueOrNone(any(Frais.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(fraisDao.findUniqueOrNone(any(Frais.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        fraisRepositoryImpl.findUniqueOrNone(new Frais());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(fraisDao.findUnique(any(Frais.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        fraisRepositoryImpl.findUnique(new Frais());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Frais unique = new Frais();

        when(fraisDao.findUnique(any(Frais.class), any(SearchParameters.class))).thenReturn(unique);

        Frais result = fraisRepositoryImpl.findUnique(new Frais());

        assertThat(result).isNotNull();
        verify(fraisDao, times(1)).findUnique(any(Frais.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(fraisDao.findUnique(any(Frais.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        fraisRepositoryImpl.findUnique(new Frais());
    }
}