/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafadministration.repository;

import java.util.Date;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafadministration.domain.Frais;
import com.eldoraludo.ppafadministration.domain.Membreppaf;
import com.eldoraludo.ppafadministration.repository.MembreppafGenerator;
import com.eldoraludo.ppafadministration.repository.MembreppafRepository;
import com.eldoraludo.ppafadministration.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class FraisGenerator {

    /**
     * Returns a new Frais instance filled with random values.
     */
    public Frais getFrais() {
        Frais frais = new Frais();

        // simple attributes follows
        frais.setMontant(1d);
        frais.setDate(new Date());
        frais.setModedereglement("a");
        frais.setInformationreglement("a");
        // mandatory relation
        Membreppaf membreppaf = membreppafGenerator.getMembreppaf();
        membreppafRepository.save(membreppaf);
        frais.setMembreppaf(membreppaf);
        return frais;
    }

    @Inject
    private MembreppafRepository membreppafRepository;
    @Inject
    private MembreppafGenerator membreppafGenerator;
}