/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafadministration.repository;

import java.util.Date;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafadministration.domain.Item;
import com.eldoraludo.ppafadministration.domain.Membreppaf;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.eldoraludo.ppafadministration.repository.ItemGenerator;
import com.eldoraludo.ppafadministration.repository.ItemRepository;
import com.eldoraludo.ppafadministration.repository.MembreppafGenerator;
import com.eldoraludo.ppafadministration.repository.MembreppafRepository;
import com.eldoraludo.ppafadministration.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class VenteGenerator {

    /**
     * Returns a new Vente instance filled with random values.
     */
    public Vente getVente() {
        Vente vente = new Vente();

        // simple attributes follows
        vente.setDate(new Date());
        vente.setDatedencaissement(new Date());
        vente.setQuantite(1);
        vente.setPrixtotal(1d);
        vente.setFraisdeport(1d);
        vente.setNumerodefacture("a");
        vente.setModedereglement("a");
        vente.setInformationreglement("a");
        vente.setNote("a");
        // mandatory relation
        Item item = itemGenerator.getItem();
        itemRepository.save(item);
        vente.setItem(item);
        // mandatory relation
        Membreppaf membreppaf = membreppafGenerator.getMembreppaf();
        membreppafRepository.save(membreppaf);
        vente.setMembreppaf(membreppaf);
        return vente;
    }

    @Inject
    private ItemRepository itemRepository;
    @Inject
    private ItemGenerator itemGenerator;
    @Inject
    private MembreppafRepository membreppafRepository;
    @Inject
    private MembreppafGenerator membreppafGenerator;
}