/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafadministration.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafadministration.domain.Vente;
import com.eldoraludo.ppafadministration.repository.VenteRepositoryImpl;
import com.eldoraludo.ppafadministration.dao.VenteDao;
import com.eldoraludo.ppafadministration.dao.support.SearchParameters;

/**
 * Unit test on VenteRepositoryImpl
 */
public class VenteRepositoryImplTest {

    private VenteRepositoryImpl venteRepositoryImpl;
    private VenteDao venteDao;

    @Before
    public void setUp() {
        // called before each test.
        venteRepositoryImpl = new VenteRepositoryImpl();
        venteDao = mock(VenteDao.class);
        venteRepositoryImpl.setVenteDao(venteDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Vente none = null;

        when(venteDao.findUniqueOrNone(any(Vente.class), any(SearchParameters.class))).thenReturn(none);

        Vente result = venteRepositoryImpl.findUniqueOrNone(new Vente());

        assertThat(result).isNull();
        verify(venteDao, times(1)).findUniqueOrNone(any(Vente.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Vente unique = new Vente();

        when(venteDao.findUniqueOrNone(any(Vente.class), any(SearchParameters.class))).thenReturn(unique);

        Vente result = venteRepositoryImpl.findUniqueOrNone(new Vente());

        assertThat(result).isNotNull();
        verify(venteDao, times(1)).findUniqueOrNone(any(Vente.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(venteDao.findUniqueOrNone(any(Vente.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        venteRepositoryImpl.findUniqueOrNone(new Vente());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(venteDao.findUnique(any(Vente.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        venteRepositoryImpl.findUnique(new Vente());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Vente unique = new Vente();

        when(venteDao.findUnique(any(Vente.class), any(SearchParameters.class))).thenReturn(unique);

        Vente result = venteRepositoryImpl.findUnique(new Vente());

        assertThat(result).isNotNull();
        verify(venteDao, times(1)).findUnique(any(Vente.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(venteDao.findUnique(any(Vente.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        venteRepositoryImpl.findUnique(new Vente());
    }
}