/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafadministration.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafadministration.dao.support.GenericDao;
import com.eldoraludo.ppafadministration.repository.support.RepositoryImpl;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.eldoraludo.ppafadministration.dao.VenteDao;

/**
 * Default implementation of the {@link VenteRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see VenteRepository
 */
@Named("venteRepository")
@Singleton
public class VenteRepositoryImpl extends RepositoryImpl<Vente, Integer> implements VenteRepository {

    private static final Logger log = Logger.getLogger(VenteRepositoryImpl.class);

    protected VenteDao venteDao;

    @Inject
    public void setVenteDao(VenteDao venteDao) {
        this.venteDao = venteDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Vente, Integer> getDao() {
        return venteDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vente getNew() {
        return new Vente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vente getNewWithDefaults() {
        Vente result = getNew();
        result.initDefaultValues();
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void delete(Vente vente) {
        if (vente == null) {
            if (log.isDebugEnabled()) {
                log.debug("Skipping deletion for null model!");
            }

            return;
        }

        // remove the reference from the associated item
        if (vente.getItem() != null) {
            vente.getItem().removeVente(vente);
        }

        // remove the reference from the associated membreppaf
        if (vente.getMembreppaf() != null) {
            vente.getMembreppaf().removeVente(vente);
        }

        // remove the reference from the associated lieudedepot
        if (vente.getLieudedepot() != null) {
            vente.getLieudedepot().removeVente(vente);
        }

        // remove the reference from the associated contact
        if (vente.getContact() != null) {
            vente.getContact().removeVente(vente);
        }

        super.delete(vente);
    }
}