/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.eldoraludo.ppafadministration.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafadministration.domain.Frais;
import com.eldoraludo.ppafadministration.repository.FraisGenerator;
import com.eldoraludo.ppafadministration.dao.FraisDao;

/**
 * Integration test on FraisDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class FraisDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(FraisDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private FraisDao fraisDao;

    @Inject
    private FraisGenerator fraisGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Frais frais = fraisGenerator.getFrais();

        // add it to a Set before saving (force equals/hashcode)
        Set<Frais> set = newHashSet(frais, frais);
        assertThat(set).hasSize(1);

        fraisDao.save(frais);
        entityManager.flush();

        // reload it from cache and check equality
        Frais model = new Frais();
        model.setId(frais.getId());
        assertThat(frais).isEqualTo(fraisDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(frais.getId()).isEqualTo(fraisDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(frais).isNotEqualTo(fraisDao.get(model));
    }
}