/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.eldoraludo.ppafadministration.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.eldoraludo.ppafadministration.util.*;
import static javax.persistence.CascadeType.ALL;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.NotEmpty;
import com.eldoraludo.ppafadministration.domain.Suividulieudedepot;
import com.eldoraludo.ppafadministration.domain.Vente;

/**
 * Basic tests for Lieudedepot
 */
@SuppressWarnings("unused")
public class LieudedepotTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Lieudedepot model = new Lieudedepot();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        Lieudedepot model = new Lieudedepot();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // One to Many: SimpleOneToMany LIEUDEDEPOT.ID ==> SUIVIDULIEUDEDEPOT.lieuDeDepot_id
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // suividulieudedepot.suividulieudedepot <-- lieudedepot.lieudedepots
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addSuividulieudedepot() {
        Lieudedepot one = new Lieudedepot();
        Suividulieudedepot many = new Suividulieudedepot();

        // init
        one.addSuividulieudedepot(many);

        // make sure it is propagated
        assertTrue(one.containsSuividulieudedepot(many));
        assertTrue(one.equals(many.getLieudedepot()));

        // now set it to null
        one.removeSuividulieudedepot(many);

        // make sure null is propagated
        assertFalse(one.containsSuividulieudedepot(many));
        assertNull(many.getLieudedepot());
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // vente.vente <-- lieudedepot.lieudedepots
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void oneToMany_addVente() {
        Lieudedepot one = new Lieudedepot();
        Vente many = new Vente();

        // init
        one.addVente(many);

        // make sure it is propagated
        assertTrue(one.containsVente(many));
        assertTrue(one.equals(many.getLieudedepot()));

        // now set it to null
        one.removeVente(many);

        // make sure null is propagated
        assertFalse(one.containsVente(many));
        assertNull(many.getLieudedepot());
    }

    @Test
    public void toStringNotNull() {
        Lieudedepot model = new Lieudedepot();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingBusinessKey() {
        Lieudedepot model1 = new Lieudedepot();
        Lieudedepot model2 = new Lieudedepot();
        String nom = "a";
        model1.setNom(nom);
        model2.setNom(nom);
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
        assertTrue(model1.hashCode() == model2.hashCode());
    }
}