/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.eldoraludo.ppafadministration.domain;

import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.DATE;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import com.eldoraludo.ppafadministration.domain.Membreppaf;
import com.eldoraludo.ppafadministration.domain.PersistableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "FRAIS")
@Cache(usage = NONSTRICT_READ_WRITE)
public class Frais implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Frais.class);

    // Raw attributes
    private Integer id; // pk
    private Double montant; // not null
    private Date date; // not null
    private String modedereglement;
    private String informationreglement;
    private Integer version;

    // Technical attributes for query by example
    private Integer membreppafId; // not null

    // Many to one
    private Membreppaf membreppaf; // not null (membreppafId)

    // ---------------------------
    // Constructors
    // ---------------------------

    public Frais() {
    }

    public Frais(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [montant] ------------------------

    @NotNull
    @Column(name = "MONTANT", nullable = false, precision = 17)
    public Double getMontant() {
        return montant;
    }

    public void setMontant(Double montant) {
        this.montant = montant;
    }

    /**
     * Helper method to set the montant attribute via an int.
     * @see #setMontant(Double)
     */
    public void setMontant(int montant) {
        this.montant = Double.valueOf(montant);
    }

    // -- [date] ------------------------

    @NotNull
    @Column(name = "`DATE`", nullable = false, length = 8)
    @Temporal(DATE)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    // -- [modedereglement] ------------------------

    @Size(max = 255)
    @Column(name = "modeDeReglement")
    public String getModedereglement() {
        return modedereglement;
    }

    public void setModedereglement(String modedereglement) {
        this.modedereglement = modedereglement;
    }

    // -- [informationreglement] ------------------------

    @Size(max = 255)
    @Column(name = "informationReglement")
    public String getInformationreglement() {
        return informationreglement;
    }

    public void setInformationreglement(String informationreglement) {
        this.informationreglement = informationreglement;
    }

    // -- [membreppafId] ------------------------

    @Column(name = "membrePPAF_id", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getMembreppafId() {
        return membreppafId;
    }

    private void setMembreppafId(Integer membreppafId) {
        this.membreppafId = membreppafId;
    }

    // -- [version] ------------------------

    @Column(name = "VERSION", precision = 10)
    @Version
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    // --------------------------------------------------------------------
    // Many to One support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Frais.membreppafId ==> Membreppaf.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @Cache(usage = NONSTRICT_READ_WRITE)
    @JoinColumn(name = "membrePPAF_id", nullable = false)
    @ManyToOne(cascade = PERSIST, fetch = LAZY)
    public Membreppaf getMembreppaf() {
        return membreppaf;
    }

    /**
     * Set the membreppaf without adding this Frais instance on the passed membreppaf
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Membreppaf}
     */
    public void setMembreppaf(Membreppaf membreppaf) {
        this.membreppaf = membreppaf;

        // We set the foreign key property so it can be used by our JPA search by Example facility.
        if (membreppaf != null) {
            setMembreppafId(membreppaf.getId());
        } else {
            setMembreppafId(null);
        }
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Frais && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Frais instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("montant", getMontant()) //
                .add("date", getDate()) //
                .add("modedereglement", getModedereglement()) //
                .add("informationreglement", getInformationreglement()) //
                .add("membreppafId", getMembreppafId()) //
                .add("version", getVersion()) //
                .toString();
    }
}