/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.eldoraludo.ppafadministration.domain;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.eldoraludo.ppafadministration.domain.Membreppaf;

@StaticMetamodel(Frais.class)
public abstract class Frais_ {

    // Raw attributes
    public static volatile SingularAttribute<Frais, Integer> id;
    public static volatile SingularAttribute<Frais, Double> montant;
    public static volatile SingularAttribute<Frais, Date> date;
    public static volatile SingularAttribute<Frais, String> modedereglement;
    public static volatile SingularAttribute<Frais, String> informationreglement;

    // Technical attributes for query by example
    public static volatile SingularAttribute<Frais, Integer> membreppafId;

    // Many to one
    public static volatile SingularAttribute<Frais, Membreppaf> membreppaf;
}