/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.eldoraludo.ppafadministration.domain;

import static javax.persistence.CascadeType.ALL;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.NotEmpty;
import com.eldoraludo.ppafadministration.domain.Suividulieudedepot;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.google.common.base.Objects;

@Entity
@Table(name = "LIEUDEDEPOT")
@Cache(usage = NONSTRICT_READ_WRITE)
public class Lieudedepot implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Lieudedepot.class);

    // Raw attributes
    private Integer id; // pk
    private String nom; // not null
    private String numerotelephone1;
    private String numerotelephone2;
    private String rue;
    private String ville;
    private String codepostal;
    private String infosuppl;
    private String type;

    // One to many
    private List<Suividulieudedepot> suividulieudedepots = new ArrayList<Suividulieudedepot>();
    private List<Vente> ventes = new ArrayList<Vente>();

    // ---------------------------
    // Constructors
    // ---------------------------

    public Lieudedepot() {
    }

    public Lieudedepot(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [nom] ------------------------

    @Size(max = 255)
    @NotEmpty
    @Column(nullable = false)
    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    // -- [numerotelephone1] ------------------------

    @Size(max = 255)
    @Column(name = "numeroTelephone1")
    public String getNumerotelephone1() {
        return numerotelephone1;
    }

    public void setNumerotelephone1(String numerotelephone1) {
        this.numerotelephone1 = numerotelephone1;
    }

    // -- [numerotelephone2] ------------------------

    @Size(max = 255)
    @Column(name = "numeroTelephone2")
    public String getNumerotelephone2() {
        return numerotelephone2;
    }

    public void setNumerotelephone2(String numerotelephone2) {
        this.numerotelephone2 = numerotelephone2;
    }

    // -- [rue] ------------------------

    @Size(max = 255)
    @Column(name = "RUE")
    public String getRue() {
        return rue;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    // -- [ville] ------------------------

    @Size(max = 255)
    @Column(name = "VILLE")
    public String getVille() {
        return ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    // -- [codepostal] ------------------------

    @Size(max = 255)
    @Column(name = "codePostal")
    public String getCodepostal() {
        return codepostal;
    }

    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }

    // -- [infosuppl] ------------------------

    @Size(max = 2147483647)
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "infoSuppl")
    @Lob
    public String getInfosuppl() {
        return infosuppl;
    }

    public void setInfosuppl(String infosuppl) {
        this.infosuppl = infosuppl;
    }

    // -- [type] ------------------------

    @Size(max = 255)
    @Column(name = "`TYPE`")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // --------------------------------------------------------------------
    // One to Many support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: lieudedepot ==> suividulieudedepots
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "lieudedepot", orphanRemoval = true, cascade = ALL)
    public List<Suividulieudedepot> getSuividulieudedepots() {
        return suividulieudedepots;
    }

    /**
     * Set the {@link Suividulieudedepot} list.
     * It is recommended to use the helper method {@link #addSuividulieudedepot(Suividulieudedepot)} / {@link #removeSuividulieudedepot(Suividulieudedepot)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param suividulieudedepots the list to set
     */
    public void setSuividulieudedepots(List<Suividulieudedepot> suividulieudedepots) {
        this.suividulieudedepots = suividulieudedepots;
    }

    /**
     * Helper method to add the passed {@link Suividulieudedepot} to the suividulieudedepots list
     * and set this lieudedepot on the passed suividulieudedepot to preserve referential
     * integrity at the object level.
     *
     * @param suividulieudedepot the to add
     * @return true if the suividulieudedepot could be added to the suividulieudedepots list, false otherwise
     */
    public boolean addSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        if (getSuividulieudedepots().add(suividulieudedepot)) {
            suividulieudedepot.setLieudedepot((Lieudedepot) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Suividulieudedepot} is already present in the suividulieudedepots list.
     *
     * @param suividulieudedepot the instance to look up.
     * @return true if the suividulieudedepots list contains the passed suividulieudedepot, false otherwise.
     */
    public boolean containsSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        return getSuividulieudedepots() != null && getSuividulieudedepots().contains(suividulieudedepot);
    }

    /**
     * Helper method to remove the passed {@link Suividulieudedepot} from the suividulieudedepots list and unset
     * this lieudedepot from the passed suividulieudedepot to preserve referential integrity at the object level.
     *
     * @param suividulieudedepot the instance to remove
     * @return true if the suividulieudedepot could be removed from the suividulieudedepots list, false otherwise
     */
    public boolean removeSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        if (getSuividulieudedepots().remove(suividulieudedepot)) {
            suividulieudedepot.setLieudedepot(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: lieudedepot ==> ventes
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "lieudedepot", orphanRemoval = true, cascade = ALL)
    public List<Vente> getVentes() {
        return ventes;
    }

    /**
     * Set the {@link Vente} list.
     * It is recommended to use the helper method {@link #addVente(Vente)} / {@link #removeVente(Vente)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param ventes the list to set
     */
    public void setVentes(List<Vente> ventes) {
        this.ventes = ventes;
    }

    /**
     * Helper method to add the passed {@link Vente} to the ventes list
     * and set this lieudedepot on the passed vente to preserve referential
     * integrity at the object level.
     *
     * @param vente the to add
     * @return true if the vente could be added to the ventes list, false otherwise
     */
    public boolean addVente(Vente vente) {
        if (getVentes().add(vente)) {
            vente.setLieudedepot((Lieudedepot) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Vente} is already present in the ventes list.
     *
     * @param vente the instance to look up.
     * @return true if the ventes list contains the passed vente, false otherwise.
     */
    public boolean containsVente(Vente vente) {
        return getVentes() != null && getVentes().contains(vente);
    }

    /**
     * Helper method to remove the passed {@link Vente} from the ventes list and unset
     * this lieudedepot from the passed vente to preserve referential integrity at the object level.
     *
     * @param vente the instance to remove
     * @return true if the vente could be removed from the ventes list, false otherwise
     */
    public boolean removeVente(Vente vente) {
        if (getVentes().remove(vente)) {
            vente.setLieudedepot(null);
            return true;
        }
        return false;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Lieudedepot && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getNom());
        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warn("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this Lieudedepot instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("nom", getNom()) //
                .add("numerotelephone1", getNumerotelephone1()) //
                .add("numerotelephone2", getNumerotelephone2()) //
                .add("rue", getRue()) //
                .add("ville", getVille()) //
                .add("codepostal", getCodepostal()) //
                .add("infosuppl", getInfosuppl()) //
                .add("type", getType()) //
                .toString();
    }
}