/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.eldoraludo.ppafadministration.domain;

import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import com.eldoraludo.ppafadministration.domain.Frais;
import com.eldoraludo.ppafadministration.domain.PersistableHashBuilder;
import com.eldoraludo.ppafadministration.domain.Rolemembre;
import com.eldoraludo.ppafadministration.domain.Suivicontact;
import com.eldoraludo.ppafadministration.domain.Suividulieudedepot;
import com.eldoraludo.ppafadministration.domain.Utilisateur;
import com.eldoraludo.ppafadministration.domain.Vente;
import com.google.common.base.Objects;

@Entity
@Table(name = "MEMBREPPAF")
@Cache(usage = NONSTRICT_READ_WRITE)
public class Membreppaf implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Membreppaf.class);

    // Raw attributes
    private Integer id; // pk
    private String nom; // not null
    private String prenom; // not null
    private String numerotelephone1;
    private String numerotelephone2;
    private String email;
    private Boolean actif; // not null
    private String note;
    private String rue;
    private String ville;
    private String codepostal;
    private String infosuppl;

    // Technical attributes for query by example
    private Integer rolemembreId; // not null

    // Many to one
    private Rolemembre rolemembre; // not null (rolemembreId)

    // One to many
    private List<Utilisateur> utilisateurs = new ArrayList<Utilisateur>();
    private List<Suivicontact> suivicontacts = new ArrayList<Suivicontact>();
    private List<Suividulieudedepot> suividulieudedepots = new ArrayList<Suividulieudedepot>();
    private List<Vente> ventes = new ArrayList<Vente>();
    private List<Frais> fraiss = new ArrayList<Frais>();

    // ---------------------------
    // Constructors
    // ---------------------------

    public Membreppaf() {
    }

    public Membreppaf(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [nom] ------------------------

    @Size(max = 255)
    @NotEmpty
    @Column(name = "NOM", nullable = false)
    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    // -- [prenom] ------------------------

    @Size(max = 255)
    @NotEmpty
    @Column(name = "PRENOM", nullable = false)
    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    // -- [numerotelephone1] ------------------------

    @Size(max = 255)
    @Column(name = "NUMEROTELEPHONE1")
    public String getNumerotelephone1() {
        return numerotelephone1;
    }

    public void setNumerotelephone1(String numerotelephone1) {
        this.numerotelephone1 = numerotelephone1;
    }

    // -- [numerotelephone2] ------------------------

    @Size(max = 255)
    @Column(name = "NUMEROTELEPHONE2")
    public String getNumerotelephone2() {
        return numerotelephone2;
    }

    public void setNumerotelephone2(String numerotelephone2) {
        this.numerotelephone2 = numerotelephone2;
    }

    // -- [email] ------------------------

    @Size(max = 255)
    @Email
    @Column(name = "EMAIL")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // -- [actif] ------------------------

    @NotNull
    @Column(name = "ACTIF", nullable = false, length = 1)
    public Boolean getActif() {
        return actif;
    }

    public void setActif(Boolean actif) {
        this.actif = actif;
    }

    // -- [note] ------------------------

    @Size(max = 2147483647)
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "NOTE")
    @Lob
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    // -- [rue] ------------------------

    @Size(max = 255)
    @Column(name = "RUE")
    public String getRue() {
        return rue;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    // -- [ville] ------------------------

    @Size(max = 255)
    @Column(name = "VILLE")
    public String getVille() {
        return ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    // -- [codepostal] ------------------------

    @Size(max = 255)
    @Column(name = "CODEPOSTAL")
    public String getCodepostal() {
        return codepostal;
    }

    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }

    // -- [infosuppl] ------------------------

    @Size(max = 2147483647)
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "INFOSUPPL")
    @Lob
    public String getInfosuppl() {
        return infosuppl;
    }

    public void setInfosuppl(String infosuppl) {
        this.infosuppl = infosuppl;
    }

    // -- [rolemembreId] ------------------------

    @Column(name = "ROLEMEMBRE_ID", nullable = false, precision = 10, insertable = false, updatable = false)
    public Integer getRolemembreId() {
        return rolemembreId;
    }

    private void setRolemembreId(Integer rolemembreId) {
        this.rolemembreId = rolemembreId;
    }

    // --------------------------------------------------------------------
    // Many to One support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Membreppaf.rolemembreId ==> Rolemembre.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @Cache(usage = NONSTRICT_READ_WRITE)
    @JoinColumn(name = "ROLEMEMBRE_ID", nullable = false)
    @ManyToOne(cascade = PERSIST, fetch = LAZY)
    public Rolemembre getRolemembre() {
        return rolemembre;
    }

    /**
     * Set the rolemembre without adding this Membreppaf instance on the passed rolemembre
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Rolemembre}
     */
    public void setRolemembre(Rolemembre rolemembre) {
        this.rolemembre = rolemembre;

        // We set the foreign key property so it can be used by our JPA search by Example facility.
        if (rolemembre != null) {
            setRolemembreId(rolemembre.getId());
        } else {
            setRolemembreId(null);
        }
    }

    // --------------------------------------------------------------------
    // One to Many support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: membreppaf ==> utilisateurs
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "membreppaf", orphanRemoval = true, cascade = ALL)
    public List<Utilisateur> getUtilisateurs() {
        return utilisateurs;
    }

    /**
     * Set the {@link Utilisateur} list.
     * It is recommended to use the helper method {@link #addUtilisateur(Utilisateur)} / {@link #removeUtilisateur(Utilisateur)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param utilisateurs the list to set
     */
    public void setUtilisateurs(List<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }

    /**
     * Helper method to add the passed {@link Utilisateur} to the utilisateurs list
     * and set this membreppaf on the passed utilisateur to preserve referential
     * integrity at the object level.
     *
     * @param utilisateur the to add
     * @return true if the utilisateur could be added to the utilisateurs list, false otherwise
     */
    public boolean addUtilisateur(Utilisateur utilisateur) {
        if (getUtilisateurs().add(utilisateur)) {
            utilisateur.setMembreppaf((Membreppaf) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Utilisateur} is already present in the utilisateurs list.
     *
     * @param utilisateur the instance to look up.
     * @return true if the utilisateurs list contains the passed utilisateur, false otherwise.
     */
    public boolean containsUtilisateur(Utilisateur utilisateur) {
        return getUtilisateurs() != null && getUtilisateurs().contains(utilisateur);
    }

    /**
     * Helper method to remove the passed {@link Utilisateur} from the utilisateurs list and unset
     * this membreppaf from the passed utilisateur to preserve referential integrity at the object level.
     *
     * @param utilisateur the instance to remove
     * @return true if the utilisateur could be removed from the utilisateurs list, false otherwise
     */
    public boolean removeUtilisateur(Utilisateur utilisateur) {
        if (getUtilisateurs().remove(utilisateur)) {
            utilisateur.setMembreppaf(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: membreppaf ==> suivicontacts
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "membreppaf", orphanRemoval = true, cascade = ALL)
    public List<Suivicontact> getSuivicontacts() {
        return suivicontacts;
    }

    /**
     * Set the {@link Suivicontact} list.
     * It is recommended to use the helper method {@link #addSuivicontact(Suivicontact)} / {@link #removeSuivicontact(Suivicontact)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param suivicontacts the list to set
     */
    public void setSuivicontacts(List<Suivicontact> suivicontacts) {
        this.suivicontacts = suivicontacts;
    }

    /**
     * Helper method to add the passed {@link Suivicontact} to the suivicontacts list
     * and set this membreppaf on the passed suivicontact to preserve referential
     * integrity at the object level.
     *
     * @param suivicontact the to add
     * @return true if the suivicontact could be added to the suivicontacts list, false otherwise
     */
    public boolean addSuivicontact(Suivicontact suivicontact) {
        if (getSuivicontacts().add(suivicontact)) {
            suivicontact.setMembreppaf((Membreppaf) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Suivicontact} is already present in the suivicontacts list.
     *
     * @param suivicontact the instance to look up.
     * @return true if the suivicontacts list contains the passed suivicontact, false otherwise.
     */
    public boolean containsSuivicontact(Suivicontact suivicontact) {
        return getSuivicontacts() != null && getSuivicontacts().contains(suivicontact);
    }

    /**
     * Helper method to remove the passed {@link Suivicontact} from the suivicontacts list and unset
     * this membreppaf from the passed suivicontact to preserve referential integrity at the object level.
     *
     * @param suivicontact the instance to remove
     * @return true if the suivicontact could be removed from the suivicontacts list, false otherwise
     */
    public boolean removeSuivicontact(Suivicontact suivicontact) {
        if (getSuivicontacts().remove(suivicontact)) {
            suivicontact.setMembreppaf(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: membreppaf ==> suividulieudedepots
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "membreppaf", orphanRemoval = true, cascade = ALL)
    public List<Suividulieudedepot> getSuividulieudedepots() {
        return suividulieudedepots;
    }

    /**
     * Set the {@link Suividulieudedepot} list.
     * It is recommended to use the helper method {@link #addSuividulieudedepot(Suividulieudedepot)} / {@link #removeSuividulieudedepot(Suividulieudedepot)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param suividulieudedepots the list to set
     */
    public void setSuividulieudedepots(List<Suividulieudedepot> suividulieudedepots) {
        this.suividulieudedepots = suividulieudedepots;
    }

    /**
     * Helper method to add the passed {@link Suividulieudedepot} to the suividulieudedepots list
     * and set this membreppaf on the passed suividulieudedepot to preserve referential
     * integrity at the object level.
     *
     * @param suividulieudedepot the to add
     * @return true if the suividulieudedepot could be added to the suividulieudedepots list, false otherwise
     */
    public boolean addSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        if (getSuividulieudedepots().add(suividulieudedepot)) {
            suividulieudedepot.setMembreppaf((Membreppaf) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Suividulieudedepot} is already present in the suividulieudedepots list.
     *
     * @param suividulieudedepot the instance to look up.
     * @return true if the suividulieudedepots list contains the passed suividulieudedepot, false otherwise.
     */
    public boolean containsSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        return getSuividulieudedepots() != null && getSuividulieudedepots().contains(suividulieudedepot);
    }

    /**
     * Helper method to remove the passed {@link Suividulieudedepot} from the suividulieudedepots list and unset
     * this membreppaf from the passed suividulieudedepot to preserve referential integrity at the object level.
     *
     * @param suividulieudedepot the instance to remove
     * @return true if the suividulieudedepot could be removed from the suividulieudedepots list, false otherwise
     */
    public boolean removeSuividulieudedepot(Suividulieudedepot suividulieudedepot) {
        if (getSuividulieudedepots().remove(suividulieudedepot)) {
            suividulieudedepot.setMembreppaf(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: membreppaf ==> ventes
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "membreppaf", orphanRemoval = true, cascade = ALL)
    public List<Vente> getVentes() {
        return ventes;
    }

    /**
     * Set the {@link Vente} list.
     * It is recommended to use the helper method {@link #addVente(Vente)} / {@link #removeVente(Vente)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param ventes the list to set
     */
    public void setVentes(List<Vente> ventes) {
        this.ventes = ventes;
    }

    /**
     * Helper method to add the passed {@link Vente} to the ventes list
     * and set this membreppaf on the passed vente to preserve referential
     * integrity at the object level.
     *
     * @param vente the to add
     * @return true if the vente could be added to the ventes list, false otherwise
     */
    public boolean addVente(Vente vente) {
        if (getVentes().add(vente)) {
            vente.setMembreppaf((Membreppaf) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Vente} is already present in the ventes list.
     *
     * @param vente the instance to look up.
     * @return true if the ventes list contains the passed vente, false otherwise.
     */
    public boolean containsVente(Vente vente) {
        return getVentes() != null && getVentes().contains(vente);
    }

    /**
     * Helper method to remove the passed {@link Vente} from the ventes list and unset
     * this membreppaf from the passed vente to preserve referential integrity at the object level.
     *
     * @param vente the instance to remove
     * @return true if the vente could be removed from the ventes list, false otherwise
     */
    public boolean removeVente(Vente vente) {
        if (getVentes().remove(vente)) {
            vente.setMembreppaf(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: membreppaf ==> fraiss
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Cache(usage = NONSTRICT_READ_WRITE)
    @OneToMany(mappedBy = "membreppaf", orphanRemoval = true, cascade = ALL)
    public List<Frais> getFraiss() {
        return fraiss;
    }

    /**
     * Set the {@link Frais} list.
     * It is recommended to use the helper method {@link #addFrais(Frais)} / {@link #removeFrais(Frais)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param fraiss the list to set
     */
    public void setFraiss(List<Frais> fraiss) {
        this.fraiss = fraiss;
    }

    /**
     * Helper method to add the passed {@link Frais} to the fraiss list
     * and set this membreppaf on the passed frais to preserve referential
     * integrity at the object level.
     *
     * @param frais the to add
     * @return true if the frais could be added to the fraiss list, false otherwise
     */
    public boolean addFrais(Frais frais) {
        if (getFraiss().add(frais)) {
            frais.setMembreppaf((Membreppaf) this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to determine if the passed {@link Frais} is already present in the fraiss list.
     *
     * @param frais the instance to look up.
     * @return true if the fraiss list contains the passed frais, false otherwise.
     */
    public boolean containsFrais(Frais frais) {
        return getFraiss() != null && getFraiss().contains(frais);
    }

    /**
     * Helper method to remove the passed {@link Frais} from the fraiss list and unset
     * this membreppaf from the passed frais to preserve referential integrity at the object level.
     *
     * @param frais the instance to remove
     * @return true if the frais could be removed from the fraiss list, false otherwise
     */
    public boolean removeFrais(Frais frais) {
        if (getFraiss().remove(frais)) {
            frais.setMembreppaf(null);
            return true;
        }
        return false;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Membreppaf && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Membreppaf instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("nom", getNom()) //
                .add("prenom", getPrenom()) //
                .add("numerotelephone1", getNumerotelephone1()) //
                .add("numerotelephone2", getNumerotelephone2()) //
                .add("email", getEmail()) //
                .add("actif", getActif()) //
                .add("note", getNote()) //
                .add("rue", getRue()) //
                .add("ville", getVille()) //
                .add("codepostal", getCodepostal()) //
                .add("infosuppl", getInfosuppl()) //
                .add("rolemembreId", getRolemembreId()) //
                .toString();
    }
}